### ISSUE TITLE
ahhhhh i need help

### ISSUE THREAD

**Issue by hades-dev-2b2t** [DivineEnergylol/IntentBase#1]
i need help its not building or not able to run.

**Comment by DivineEnergylol** [comment]
whats ur discord

**Comment by qe7** [comment]
I think, now this is only a thought... he thinks this is a 1.12 client base for 2b

**Comment by DivineEnergylol** [comment]
ah makes sense

**Comment by hades-dev-2b2t** [comment]
no dude its not a base for a 1.12.2 i need to make my own 1.8 client and anyways here is my discord Deleted User 2c35fe#0001

**Comment by DivineEnergylol** [comment]
> LOL

ur suck a ~~faggot~~ weirdo that you edited ur message of you being retarded

**Comment by WinterTempIQ** [comment]
![image](https://user-images.githubusercontent.com/91818850/155410505-5ae6558a-3ce5-424e-b72f-4dd1d5714f23.png)

**Comment by DivineEnergylol** [comment]
LOOOL
